- name: prepare some dirs
  file: name={{ item }} state=directory
  with_items: 
  - "{{ bin_dir }}"
  - "{{ ca_dir }}"

- name: 准备CA配置文件
  template: src=ca-config.json dest={{ ca_dir }}/ca-config.json

- name: 
